version: '3.8'

services:
  php:
    build: .
    container_name: php_container
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"    # Port AMQP
      - "15672:15672"  # Interface Web Management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  database:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoList
    ports:
      - "3306:3306"

  mailer:
    image: axllent/mailpit
    container_name: mailer
    restart: always
    ports:
      - "51131:1025"
      - "51132:8025"
