version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management  # Version avec interface graphique
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  # Port pour les connexions AMQP
      - "15672:15672"  # Port pour l'interface Web Management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
